name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  echo:
    name: Run main job
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        id: check_permission
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        if: steps.check_permission.outputs.has-permission

      - run: git log -n 1
        if: steps.check_permission.outputs.has-permission

      - run: node ./run.js
        if: steps.check_permission.outputs.has-permission
        env:
          NON_CRITICAL: ${{ secrets.NON_CRITICAL }}

#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
