name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  echo:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git log -n 1

      - name: Check user permission
        id: check_permission
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `check` step
      - name: Run only if user has sufficient permissions
        if: steps.check_permission.outputs.has-permission
        run: echo 'GITHUB_TOKEN is writeable!'
      - name: Run only if user has NOT sufficient permissions
        if: "! steps.check_permission.outputs.has-permission"
        run: echo 'GITHUB_TOKEN is read-only!'

      - run: node ./run.js
        env:
          NON_CRITICAL: ${{ secrets.NON_CRITICAL }}

#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
